In [1]:
import pandas as pd
from IPython.display import display
import numpy as np

In [22]:
users = pd.read_csv('C:/Users/user/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_3/data/users.csv', sep = '\t', encoding = 'koi8_r')
log = pd.read_csv('C:/Users/user/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_3/data/log.csv', header = None)
#users = pd.read_csv('C:/Users/крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_3/data/users.csv', sep = '\t', encoding = 'koi8_r')
#log = pd.read_csv('C:/Users/крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_3/data/log.csv', header = None)
log.columns = ['user_id', 'time', 'bet', 'win']
users.columns = ['user_id', 'mail', 'city']
log[['bet','win']] = log[['bet','win']].fillna(0)
def fillna_net(row):
    if row.win < 0:
        return row.win
    else:
        return row.win - row.bet

new_net = log.apply(lambda row: fillna_net(row), axis=1)  
log['net'] = new_net
users.user_id = users.user_id.apply(lambda x: x.lower())
log = log[log.user_id != '#error']
log.user_id = log.user_id.str.split(' - ').apply(lambda x: x[1])
log_and_users = pd.merge(users, log, on='user_id')
log_and_users

,user_id,mail,city,time,bet,win,net
0,user_943,Accumanst@gmail.com,Ижевск,[2019-01-06 21:06:57,0.0,0.0,0.0
1,user_943,Accumanst@gmail.com,Ижевск,[2019-01-10 12:16:22,100.0,0.0,-100.0
2,user_943,Accumanst@gmail.com,Ижевск,[2019-01-27 1:18:47,100.0,0.0,-100.0
3,user_943,Accumanst@gmail.com,Ижевск,[2019-02-10 11:09:24,100.0,5456.0,5356.0
4,user_943,Accumanst@gmail.com,Ижевск,[2019-02-12 15:09:38,300.0,5245.0,4945.0
...,...,...,...,...,...,...,...
970,user_965,Visuareda@yahoo.com,Воронеж,[2019-04-20 12:55:41,800.0,6927.0,6127.0
971,user_921,Aavast@ya.ru,Ижевск,[2019-01-07 1:05:59,0.0,0.0,0.0
972,user_921,Aavast@ya.ru,Ижевск,[2019-02-05 14:08:57,0.0,0.0,0.0
973,user_921,Aavast@ya.ru,Ижевск,[2019-02-09 23:20:21,400.0,6067.0,5667.0
974,user_921,Aavast@ya.ru,Ижевск,[2019-02-10 17:53:37,900.0,0.0,-900.0

In [23]:
log_and_users[log_and_users.win > 0].groupby('user_id').win.median().median()

5951.75

In [42]:
log_and_users.groupby('user_id').net.sum().median()

1986.0

In [44]:
log_and_users['bet_count'] = log_and_users['bet'].apply(lambda x: 1 if x > 0 else 0)
log_and_users

,user_id,mail,city,time,bet,win,net,bet_count
0,user_943,Accumanst@gmail.com,Ижевск,[2019-01-06 21:06:57,0.0,0.0,0.0,0
1,user_943,Accumanst@gmail.com,Ижевск,[2019-01-10 12:16:22,100.0,0.0,-100.0,1
2,user_943,Accumanst@gmail.com,Ижевск,[2019-01-27 1:18:47,100.0,0.0,-100.0,1
3,user_943,Accumanst@gmail.com,Ижевск,[2019-02-10 11:09:24,100.0,5456.0,5356.0,1
4,user_943,Accumanst@gmail.com,Ижевск,[2019-02-12 15:09:38,300.0,5245.0,4945.0,1
...,...,...,...,...,...,...,...,...
970,user_965,Visuareda@yahoo.com,Воронеж,[2019-04-20 12:55:41,800.0,6927.0,6127.0,1
971,user_921,Aavast@ya.ru,Ижевск,[2019-01-07 1:05:59,0.0,0.0,0.0,0
972,user_921,Aavast@ya.ru,Ижевск,[2019-02-05 14:08:57,0.0,0.0,0.0,0
973,user_921,Aavast@ya.ru,Ижевск,[2019-02-09 23:20:21,400.0,6067.0,5667.0,1
974,user_921,Aavast@ya.ru,Ижевск,[2019-02-10 17:53:37,900.0,0.0,-900.0,1