In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
from IPython.display import display
from itertools import combinations

In [12]:
data = pd.read_csv('C:/Users/user/Documents/GitHub/Skillfactory_Alexander_Stratoonv/module_1/movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
746,tt1478338,32500000,288383523,Bridesmaids,Kristen Wiig|Rose Byrne|Maya Rudolph|Wendi McL...,Paul Feig,Save the date,Annieâ€™s life is a mess. But when she finds o...,125,Romance|Comedy,Universal Pictures|Relativity Media|Apatow Pro...,4/28/2011,6.5,2011
907,tt0160184,55000000,6416302,D-Tox,Sylvester Stallone|Courtney B. Vance|Tom Beren...,Jim Gillespie,Survival is a Killer.,A disgraced FBI agent with a drinking problem ...,96,Action|Thriller,Universal Pictures,1/4/2002,5.8,2002
639,tt0758774,70000000,113280098,Body of Lies,Leonardo DiCaprio|Russell Crowe|Mark Strong|Al...,Ridley Scott,Trust no one. Deceive everyone.,"Body of Lies follows CIA operative, Roger Ferr...",128,Action|Drama|Thriller,Scott Free Productions|De Line Pictures|Warner...,10/10/2008,6.5,2008
1204,tt1854564,90000000,174578751,Percy Jackson: Sea of Monsters,Logan Lerman|Alexandra Daddario|Douglas Smith|...,Thor Freudenthal,"Where There Are Gods, There Are Monsters.","In their quest to confront the ultimate evil, ...",106,Adventure|Family|Fantasy,1492 Pictures|Dune Entertainment|Fox 2000 Pict...,8/7/2013,5.9,2013
1119,tt0257076,80000000,116643346,S.W.A.T.,Samuel L. Jackson|Colin Farrell|Michelle Rodri...,Clark Johnson,You're either S.W.A.T. or you're not.,Hondo Harrelson recruits Jim Street to join an...,117,Action|Thriller|Crime,Original Film|Columbia Pictures Corporation|Ca...,8/8/2003,5.8,2003

In [13]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [14]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

profit = data.revenue - data.budget
data['profit'] = profit

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [15]:
answers1 = data.sort_values('budget', ascending=False)
display(answers1)
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000
1669,tt0449088,300000000,961000000,Pirates of the Caribbean: At World's End,Johnny Depp|Orlando Bloom|Keira Knightley|Geof...,Gore Verbinski,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...",169,Adventure|Fantasy|Action,Walt Disney Pictures|Jerry Bruckheimer Films|S...,5/19/2007,6.8,2007,661000000
14,tt2395427,280000000,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,Joss Whedon,A New Age Has Come.,When Tony Stark tries to jumpstart a dormant p...,141,Action|Adventure|Science Fiction,Marvel Studios|Prime Focus|Revolution Sun Studios,4/22/2015,7.4,2015,1125035767
1014,tt0401729,260000000,284139100,John Carter,Taylor Kitsch|Lynn Collins|Mark Strong|Willem ...,Andrew Stanton,Lost in Our World. Found in Another.,Civil War vet John Carter is transplanted to M...,132,Action|Adventure|Fantasy|Science Fiction,Walt Disney Pictures,3/7/2012,6.0,2012,24139100
380,tt0398286,260000000,591794936,Tangled,Zachary Levi|Mandy Moore|Donna Murphy|Ron Perl...,Nathan Greno|Byron Howard,They're taking adventure to new lengths.,When the kingdom's most wanted-and most charmi...,100,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,11/24/2010,7.3,2010,331794936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,tt0283111,5000000,38275483,National Lampoonâ€™s Van Wilder,Ryan Reynolds|Tara Reid|Tim Matheson|Kal Penn|...,Walt Becker,Don't Graduate. Celebrate.,"Van Wilder is an outgoing, and extremely popul...",92,Comedy|Romance,Tapestry Films|Artisan Entertainment,3/29/2002,5.9,2002,33275483
892,tt0259446,5000000,368744044,My Big Fat Greek Wedding,Nia Vardalos|John Corbett|Lainie Kazan|Michael...,Joel Zwick,Love is here to stay... so is her family.,A young Greek woman falls in love with a non-G...,95,Comedy|Drama|Romance,MPH Entertainment|Playtone Productions|Gold Ci...,2/22/2002,6.1,2002,363744044
1071,tt2109184,5000000,142817992,Paranormal Activity 4,Katie Featherston|Kathryn Newton|Matt Shively|...,Henry Joost|Ariel Schulman,It's closer than you think,It has been five years since the disappearance...,95,Horror,Paramount Pictures|Blumhouse Productions|Room ...,10/17/2012,5.3,2012,137817992
911,tt0322802,5000000,64282312,Jackass: The Movie,Johnny Knoxville|Bam Margera|Steve-O|Chris Pon...,Jeff Tremaine,Do not attempt this at home.,Johnny Knoxville and his crazy friends appear ...,87,Comedy,Paramount Pictures,10/21/2002,6.2,2002,59282312
1216,tt2101441,5000000,31724284,Spring Breakers,James Franco|Selena Gomez|Vanessa Hudgens|Ashl...,Harmony Korine,A little sun can bring out your dark side.,After four college girls rob a restaurant to f...,94,Drama|Crime,RabbitBandini Productions|Division Films|Pop F...,1/24/2013,5.0,2013,26724284

# 2. Какой из фильмов самый длительный (в минутах)?

In [16]:
answers2 = data.sort_values('runtime', ascending=False)
display(answers2)
answers['2'] = 'Gods and Generals (tt0279111)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979
1736,tt0462322,67000000,25037897,Grindhouse,Kurt Russell|ZoÃ« Bell|Rosario Dawson|Vanessa ...,Robert Rodriguez|Eli Roth|Quentin Tarantino|Ed...,A double feature that'll tear you in two!,Two full length feature horror movies written ...,191,Thriller|Action|Horror,Big Talk Productions|Yer Dead Productions|Wein...,4/6/2007,6.5,2007,-41962103
1336,tt0360717,207000000,550000000,King Kong,Naomi Watts|Jack Black|Adrien Brody|Thomas Kre...,Peter Jackson,The eighth wonder of the world.,"In 1933 New York, an overly ambitious movie pr...",187,Adventure|Drama|Action,WingNut Films|Universal Pictures|Big Primate P...,12/14/2005,6.4,2005,343000000
504,tt0213149,140000000,449220945,Pearl Harbor,Ben Affleck|Josh Hartnett|Kate Beckinsale|Cuba...,Michael Bay,"December 7, 1941 - A day that shall live in in...",The lifelong friendship between Rafe McCawley ...,183,History|Romance|War,Jerry Bruckheimer Films|Touchstone Pictures,5/21/2001,6.6,2001,309220945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,tt0361089,35000000,19478106,Valiant,Ewan McGregor|Ricky Gervais|Tim Curry|Jim Broa...,Gary Chapman,"Some pigeons eat crumbs, others make history.",The animated comedy tells the story of a lowly...,76,Animation|Family|Adventure,Vanguard Films|Scanbox,3/25/2005,5.3,2005,-15521894
1626,tt0299172,110000000,103951461,Home on the Range,Randy Quaid|Steve Buscemi|Judi Dench|Cuba Good...,Will Finn|John Sanford,Bust a Moo.,The Little Piece of Heaven family farm is abou...,76,Western|Animation|Family|Comedy|Music,Walt Disney Pictures|Walt Disney Feature Anima...,4/2/2004,5.8,2004,-6048539
1097,tt0283426,20000000,135680000,The Jungle Book 2,John Goodman|Haley Joel Osment|Mae Whitman|Phi...,Steve Trenbirth,Feel the jungle beat,"Mowgli, missing the jungle and his old friends...",72,Family|Animation|Adventure,Walt Disney Pictures|Walt Disney Television An...,2/7/2003,5.6,2003,115680000
930,tt0280030,20000000,109862682,Return to Never Land,Harriet Owen|Blayne Weaver|Jeff Bennett|Kath S...,Robin Budd|Donovan Cook,The Classic Continues,The classic tale of 'Peter Pan' continues in D...,72,Adventure|Fantasy|Animation|Family,Walt Disney Pictures|Walt Disney Television An...,2/14/2002,6.2,2002,89862682
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000

# 3. Какой из фильмов самый короткий (в минутах)?

In [17]:
answers3 = data.sort_values('runtime', ascending=True)
display(answers3)
answers['3'] = 'Winnie the Pooh (tt1449283)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000
930,tt0280030,20000000,109862682,Return to Never Land,Harriet Owen|Blayne Weaver|Jeff Bennett|Kath S...,Robin Budd|Donovan Cook,The Classic Continues,The classic tale of 'Peter Pan' continues in D...,72,Adventure|Fantasy|Animation|Family,Walt Disney Pictures|Walt Disney Television An...,2/14/2002,6.2,2002,89862682
1097,tt0283426,20000000,135680000,The Jungle Book 2,John Goodman|Haley Joel Osment|Mae Whitman|Phi...,Steve Trenbirth,Feel the jungle beat,"Mowgli, missing the jungle and his old friends...",72,Family|Animation|Adventure,Walt Disney Pictures|Walt Disney Television An...,2/7/2003,5.6,2003,115680000
1408,tt0361089,35000000,19478106,Valiant,Ewan McGregor|Ricky Gervais|Tim Curry|Jim Broa...,Gary Chapman,"Some pigeons eat crumbs, others make history.",The animated comedy tells the story of a lowly...,76,Animation|Family|Adventure,Vanguard Films|Scanbox,3/25/2005,5.3,2005,-15521894
1626,tt0299172,110000000,103951461,Home on the Range,Randy Quaid|Steve Buscemi|Judi Dench|Cuba Good...,Will Finn|John Sanford,Bust a Moo.,The Little Piece of Heaven family farm is abou...,76,Western|Animation|Family|Comedy|Music,Walt Disney Pictures|Walt Disney Feature Anima...,4/2/2004,5.8,2004,-6048539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,tt0213149,140000000,449220945,Pearl Harbor,Ben Affleck|Josh Hartnett|Kate Beckinsale|Cuba...,Michael Bay,"December 7, 1941 - A day that shall live in in...",The lifelong friendship between Rafe McCawley ...,183,History|Romance|War,Jerry Bruckheimer Films|Touchstone Pictures,5/21/2001,6.6,2001,309220945
1336,tt0360717,207000000,550000000,King Kong,Naomi Watts|Jack Black|Adrien Brody|Thomas Kre...,Peter Jackson,The eighth wonder of the world.,"In 1933 New York, an overly ambitious movie pr...",187,Adventure|Drama|Action,WingNut Films|Universal Pictures|Big Primate P...,12/14/2005,6.4,2005,343000000
1736,tt0462322,67000000,25037897,Grindhouse,Kurt Russell|ZoÃ« Bell|Rosario Dawson|Vanessa ...,Robert Rodriguez|Eli Roth|Quentin Tarantino|Ed...,A double feature that'll tear you in two!,Two full length feature horror movies written ...,191,Thriller|Action|Horror,Big Talk Productions|Yer Dead Productions|Wein...,4/6/2007,6.5,2007,-41962103
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064

# 4. Какова средняя длительность фильмов?

In [18]:
answers4 = data.runtime.mean()
display(answers4)
answers['4'] = '110'

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [19]:
answers5 = data.runtime.describe()
display(answers5)
answers['5'] = '107'

count    1889.000000
mean      109.658549
std        18.017041
min        63.000000
25%        97.000000
50%       107.000000
75%       120.000000
max       214.000000
Name: runtime, dtype: float64

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [20]:
answers6 = data.sort_values('profit', ascending=False)
display(answers6)
answers['6'] = 'Avatar (tt0499549)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,-84540684
958,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,-92896027
809,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,-111007242
1616,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,-119180039
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 7. Какой фильм самый убыточный?

In [21]:
answers7 = data.sort_values('profit', ascending=True)
display(answers7)
answers['7'] = 'The Lone Ranger (tt1210819)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090
1616,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,-119180039
809,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,-111007242
958,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,-92896027
1464,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,-84540684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [22]:
answers8 = data[data.revenue > data.budget]
display(answers8)
answers['8'] = '1478'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015,228436354
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015,185238201
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,tt0171433,30000000,37036004,Keeping the Faith,Ben Stiller|Edward Norton|Jenna Elfman|Anne Ba...,Edward Norton,"If you have to believe in something, you may a...","Best friends since they were kids, Rabbi Jacob...",127,Comedy,Spyglass Entertainment|Touchstone Pictures|Tri...,4/14/2000,5.7,2000,7036004
1875,tt0219854,65000000,69700000,The Kid,Bruce Willis|Spencer Breslin|Emily Mortimer|Li...,Jon Turteltaub,Nobody ever grows up quite like they imagined.,Powerful businessman Russ Duritz is self-absor...,104,Fantasy|Comedy|Family,Walt Disney Pictures,7/7/2000,5.9,2000,4700000
1877,tt0199725,20000000,27728118,Love & Basketball,"Chris Warren, Jr.|Kyla Pratt|Sanaa Lathan|Omar...",Gina Prince-Bythewood,All's fair in love and basketball.,A young African-American couple navigates the ...,124,Action|Comedy|Drama|Romance,40 Acres & A Mule Filmworks,4/21/2000,7.3,2000,7728118
1883,tt0122459,24000000,36609995,Return to Me,David Duchovny|Minnie Driver|Carroll O'Connor|...,Bonnie Hunt,A comedy straight from the heart,It took a lot of cajoling to get Bob (Duchovny...,115,Romance|Comedy|Drama,Metro-Goldwyn-Mayer (MGM)|JLT Productions,4/7/2000,5.5,2000,12609995
1884,tt0120903,75000000,157299717,X-Men,Patrick Stewart|Hugh Jackman|Ian McKellen|Hall...,Bryan Singer,Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,Adventure|Action|Science Fiction,Twentieth Century Fox Film Corporation|Donners...,7/13/2000,6.6,2000,82299717

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [23]:
answers9 = data[(data.release_year == 2008)].sort_values('profit', ascending=False)
display(answers9)
answers['9'] = 'The Dark Knight (tt0468569)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825
603,tt0367882,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,5.6,2008,601636033
607,tt0795421,52000000,609841637,Mamma Mia!,Meryl Streep|Pierce Brosnan|Amanda Seyfried|Co...,Phyllida Lloyd,Take a trip down the aisle you'll never forget,"Set on an idyllic Greek island, the plot serve...",108,Comedy|Romance,Universal Pictures|Internationale Filmprodukti...,6/30/2008,6.2,2008,557841637
606,tt0441773,130000000,631744560,Kung Fu Panda,Jack Black|Dustin Hoffman|Angelina Jolie|Jacki...,Mark Osborne|John Stevenson,Prepare for awesomeness.,"When the Valley of Peace is threatened, lazy P...",90,Animation|Family,DreamWorks Animation,6/4/2008,6.8,2008,501744560
621,tt0448157,150000000,624029371,Hancock,Will Smith|Charlize Theron|Jason Bateman|Jae H...,Peter Berg,Bad Behavior. Bad Attitude. Real Hero.,Hancock is a down-and-out superhero who's forc...,92,Fantasy|Action,Columbia Pictures|Weed Road Pictures|Forward P...,7/1/2008,6.0,2008,474029371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,tt0811080,120000000,93945766,Speed Racer,Emile Hirsch|Christina Ricci|Matthew Fox|Susan...,Lana Wachowski|Lilly Wachowski,Go!,Speed Racer is the tale of a young and brillia...,135,Family|Action|Science Fiction,Village Roadshow Pictures|Studio Babelsberg|An...,5/9/2008,5.6,2008,-26054234
705,tt0469903,40000000,9793496,The Express,Rob Brown|Dennis Quaid|Darrin Henson|Charles S...,Gary Fleder,He changed our country... one yard at a time.,"Based on the incredible true story, The Expres...",130,Drama,Davis Entertainment|Relativity Media|IDEA Film...,10/10/2008,7.1,2008,-30206504
682,tt0970411,55000000,17869048,City of Ember,Saoirse Ronan|Harry Treadaway|Mary Kay Place|B...,Gil Kenan,Escape is the only option,"For generations, the people of the City of Emb...",90,Adventure|Family|Fantasy,Playtone|Walden Media,10/7/2008,6.1,2008,-37130952
679,tt0462465,50000000,7033683,Outlander,Jim Caviezel|Sophia Myles|Jack Huston|Ron Perl...,Howard McCain,It destroyed his world. He won't let it destro...,"During the reign of the Vikings, a man from an...",115,Fantasy|Action|Science Fiction,Ascendant Pictures|Rising Star|VIP Medienfonds...,4/24/2008,6.0,2008,-42966317
636,tt0455824,130000000,49554002,Australia,Nicole Kidman|Hugh Jackman|Essie Davis|David W...,Baz Luhrmann,Welcome to Australia!,"Set in northern Australia before World War II,...",165,Drama,Bazmark Films|Ingenious Film Partners|Twentiet...,11/18/2008,6.3,2008,-80445998

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [24]:
answers10 = data[(data.release_year >= 2012) &(data.release_year <= 2014)].sort_values('profit', ascending=True)
display(answers10)
answers['10'] = 'The Lone Ranger (tt1210819)'

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090
1214,tt0790736,130000000,61648500,R.I.P.D.,Jeff Bridges|Ryan Reynolds|Kevin Bacon|Stephan...,Robert Schwentke,To protect and serve the living,A recently slain cop joins a team of undead po...,96,Fantasy|Action|Comedy|Crime,Universal Pictures|Original Film|Dark Horse En...,7/18/2013,5.3,2013,-68351500
1007,tt1374992,60000000,8106475,Upside Down,Kirsten Dunst|Jim Sturgess|Timothy Spall|James...,Juan Diego Solanas,Two worlds. One future.,In an alternate universe where twinned worlds ...,104,Romance|Science Fiction|Drama|Fantasy,Onyx Films|Studio 37|Jouror Productions|France...,9/27/2012,6.1,2012,-51893525
1302,tt0884726,70000000,18662027,Legends of Oz: Dorothy's Return,Lea Michele|Dan Aykroyd|Patrick Stewart|Hugh D...,Dan St. Pierre,There's trouble in OZ...,"Dorothy wakes up in post-tornado Kansas, only ...",88,Animation|Music|Family,Prana Animation Studios|Summertime Entertainment,6/13/2013,6.1,2013,-51337973
1235,tt1308729,55000000,9489829,Bullet to the Head,Sylvester Stallone|Sung Kang|Sarah Shahi|Adewa...,Walter Hill,Revenge Never Gets Old.,"After watching their respective partners die, ...",92,Action|Crime|Thriller,Dark Castle Entertainment|After Dark Films|IM ...,1/31/2013,5.2,2013,-45510171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,tt1690953,76000000,970761885,Despicable Me 2,Steve Carell|Kristen Wiig|Benjamin Bratt|Miran...,Pierre Coffin|Chris Renaud,Back 2 Work,Gru is recruited by the Anti-Villain League to...,98,Animation|Comedy|Family,Universal Pictures|Illumination Entertainment,6/25/2013,7.0,2013,894761885
974,tt1074638,200000000,1108561013,Skyfall,Daniel Craig|Judi Dench|Javier Bardem|Ralph Fi...,Sam Mendes,Think on your sins.,When Bond's latest assignment goes gravely wro...,143,Action|Adventure|Thriller,Columbia Pictures,10/25/2012,6.8,2012,908561013
1180,tt1300854,200000000,1215439994,Iron Man 3,Robert Downey Jr.|Gwyneth Paltrow|Guy Pearce|D...,Shane Black,Unleash the power behind the armor.,When Tony Stark's world is torn apart by a for...,130,Action|Adventure|Science Fiction,Marvel Studios,4/18/2013,6.9,2013,1015439994
1177,tt2294629,150000000,1274219009,Frozen,Kristen Bell|Idina Menzel|Jonathan Groff|Josh ...,Chris Buck|Jennifer Lee,Only the act of true love will thaw a frozen h...,Young princess Anna of Arendelle dreams about ...,102,Animation|Adventure|Family,Walt Disney Pictures|Walt Disney Animation Stu...,11/27/2013,7.5,2013,1124219009
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910

# 11. Какого жанра фильмов больше всего?

In [25]:
answers11 = pd.Series(data['genres'].str.cat(sep='|').split('|')).value_counts()
display(answers11)
answers['11'] = 'Drama'

Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [26]:
answers12 = data[data.profit > 0].copy()
answers12.genres = answers12.genres.str.split('|')
answers12 = answers12.genres.explode().value_counts()
display(answers12)
answers['12'] = 'Drama'

Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
Name: genres, dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [27]:
answers13 = data.groupby('director').sum().sort_values('profit', ascending=False)
display(answers13)
answers['13'] = 'Peter Jackson'

,budget,revenue,runtime,vote_average,release_year,profit
director,,,,,,
Peter Jackson,1288000000,6490593685,1355,58.1,16059,5202593685
David Yates,775000000,4154295625,567,29.6,8037,3379295625
Christopher Nolan,1005000000,4167548502,1135,61.1,16057,3162548502
J.J. Abrams,740000000,3579169916,633,35.1,10054,2839169916
Michael Bay,1126000000,3886938960,1209,50.0,16063,2760938960
...,...,...,...,...,...,...
Walter Hill|Jack Sholder,90000000,14828081,91,4.7,2000,-75171919
David Bowers|Sam Fell,149000000,64459316,85,6.0,2006,-84540684
Peter Hyams,120000000,33043455,214,9.9,4006,-86956545
Ron Underwood,100000000,7103973,95,4.6,2002,-92896027
James L. Brooks,200000000,103710274,251,10.5,4014,-96289726

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [28]:
answers14 = data[data.genres.str.contains("Action")]
answers14 = answers14['director'].str.cat(sep='|') 
answers14 = pd.Series(answers14.split('|')).value_counts(ascending=False) 
display(answers14)
answers['14'] = 'Robert Rodriguez'

Robert Rodriguez       9
Michael Bay            7
Paul W.S. Anderson     7
Antoine Fuqua          6
Ridley Scott           6
                      ..
Motonori Sakakibara    1
Geoffrey Sax           1
Michael Davis          1
Albert Hughes          1
Patrick Hughes         1
Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [29]:
answers15 = data.copy()
answers15.cast = data.cast.apply(lambda x: str(x).split('|'))
answers15 = answers15.explode('cast')
answers15 = answers15[answers15.release_year == 2012].groupby('cast').revenue.sum().sort_values(ascending=False)
display(answers15)
answers['15'] = 'Chris Hemsworth'

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Robert Downey Jr.    1519557910
Mark Ruffalo         1519557910
                        ...
Michael Nyqvist         3428048
Danny Huston            2106557
Josh Lucas              2106557
Sami Gayle              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [30]:
answers16 = pd.Series(data[data.budget > data.budget.mean()].cast.str.split('|').sum()).value_counts() 
display(answers16)
answers['16'] = 'Matt Damon'

Matt Damon                    18
Adam Sandler                  17
Angelina Jolie                16
Tom Cruise                    15
Samuel L. Jackson             15
                              ..
Julia Ormond                   1
Juliette Binoche               1
Ed Asner                       1
Michael-Leon Wooley            1
Salli Richardson-Whitfield     1
Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [31]:
answers17 = data[data.cast.str.contains("Nicolas Cage")].genres.str.split('|').explode().value_counts() 
display(answers17)
answers['17'] = 'Action'

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Animation           3
Mystery             3
Family              3
History             2
Horror              1
Romance             1
War                 1
Name: genres, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [32]:
answers18 = data[data['production_companies'].str.contains('Paramount Pictures')]
answers18 = answers18[['profit', 'original_title', 'imdb_id']].sort_values('profit', ascending=False)
display(answers18)
answers['18'] = 'K-19: The Widowmaker (tt0267626)'

         profit                                     original_title    imdb_id
828   928746996                     Transformers: Dark of the Moon  tt1399103
317   686297228                Transformers: Revenge of the Fallen  tt1055369
603   601636033  Indiana Jones and the Kingdom of the Crystal S...  tt0367882
1738  559709780                                       Transformers  tt0418279
730   549713380               Mission: Impossible - Ghost Protocol  tt1229238
...         ...                                                ...        ...
1631  -24805000                                            Twisted  tt0315297
1623  -46604061                                              Alfie  tt0375173
1722  -51788987                                               Next  tt0435705
1123  -60519261                                           Timeline  tt0300556
925   -64831034                               K-19: The Widowmaker  tt0267626

[122 rows x 3 columns]

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [33]:
answers19 = data.groupby(data['release_year'])['revenue'].sum().sort_values(ascending=False)
display(answers19)
answers['19'] = '2015'

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [34]:
answers20 = data[data.production_companies.str.contains("Warner Bros", na=False)].groupby(
    data['release_year'])['profit'].sum().sort_values(ascending=False)
display(answers20)
answers['20'] = '2014'

release_year
2014    2295464519
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1855493377
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1343545668
2012    1258020056
2002    1022709901
2015     870368348
2006     620170743
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [35]:
answers21 = data.release_date.str.split('/').apply(lambda x: x[0]).value_counts()
display(answers21.sort_values(ascending=False))
answers['21'] = 'Сентябрь'

9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
Name: release_date, dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [36]:
answers22 = data.release_date.str.split('/').apply(lambda x: x[0]).value_counts()
display(answers22[['6','7','8']].sum())
answers['22'] = '450'

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [37]:
answers23 = data.copy()
answers23['mouth'] = pd.DatetimeIndex(answers23['release_date']).month
answers23['directors'] = answers23.director.str.split('|')
answers23 = answers23.explode('directors')
answers23 = answers23[(answers23['mouth'] == 1) | (answers23['mouth'] == 2) | (answers23['mouth'] == 12)].value_counts(subset='directors')
answers23 = answers23.idxmax()
display(answers23)
answers['23'] = 'Peter Jackson '

'Peter Jackson'

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [38]:
answers24 = data.copy()
answers24['production_companies'] = answers24['production_companies'].str.split('|')
answers24 = answers24.explode('production_companies')
answers24['title_length'] = answers24.original_title.apply(lambda x: len(x))
answers24 = answers24.groupby('production_companies').title_length.mean().sort_values(ascending = False)
display(answers24)
answers['24'] = 'Four By Two Productions'

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Polsky Films                  46.0
Museum Canada Productions     46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
Global Entertainment Group     2.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Name: title_length, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [39]:
answers25 = data.copy()
answers25['production_companies'] = answers25['production_companies'].str.split('|')
answers25['overview'] = answers25['overview'].str.split(' ')
answers25 = answers25.explode('production_companies')
answers25['overview'] = answers25.overview.apply(lambda x: len(x))
answers25 = answers25.groupby('production_companies').overview.mean().sort_values(ascending = False)
display(answers25)
answers['25'] = 'Midnight Picture Show '

production_companies
Midnight Picture Show                    175.0
Heineken Branded Entertainment           161.0
Room 9 Entertainment                     161.0
98 MPH Productions                       159.0
Brookwell-McNamara Entertainment         156.0
                                         ...
Henceforth                                13.0
Our Stories Films                         13.0
London Boulevard                          13.0
Motion Picture Corporation of America     11.0
Empire Pictures                           11.0
Name: overview, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [40]:
answers26 = data[data['vote_average'] >= 7.9][['original_title', 'vote_average']]
display(answers26)
answers['26'] = 'Inside Out, The Dark Knight, 12 Years a Slave'

                                     original_title  vote_average
9                                        Inside Out           8.0
34                                             Room           8.0
118                                    Interstellar           8.0
119                         Guardians of the Galaxy           7.9
125                              The Imitation Game           8.0
128                                       Gone Girl           7.9
138                        The Grand Budapest Hotel           7.9
370                                       Inception           7.9
599                                 The Dark Knight           8.1
872                                     The Pianist           7.9
1081  The Lord of the Rings: The Return of the King           7.9
1183                        The Wolf of Wall Street           7.9
1191                               12 Years a Slave           7.9
1800                                        Memento           7.9

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [41]:
answers27 = data.copy()
answers27['cast_split'] = answers27['cast'].str.split('|')
answers27['cast_togever'] = answers27.cast_split.apply(lambda x: list(combinations(x, 2)))
answers27 = Counter(answers27['cast_togever'].sum()).most_common(1)
display(answers27)
answers['27'] = 'Daniel Radcliffe & Rupert Grint'

[(('Daniel Radcliffe', 'Rupert Grint'), 8)]

In [42]:
display(answers)

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals (tt0279111)',
 '3': 'Winnie the Pooh (tt1449283)',
 '4': '110',
 '5': '107',
 '6': 'Avatar (tt0499549)',
 '7': 'The Lone Ranger (tt1210819)',
 '8': '1478',
 '9': 'The Dark Knight (tt0468569)',
 '10': 'The Lone Ranger (tt1210819)',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker (tt0267626)',
 '19': '2015',
 '20': '2014',
 '21': 'Сентябрь',
 '22': '450',
 '23': 'Peter Jackson ',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show ',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave',
 '27': 'Daniel Radcliffe & Rupert Grint'}